name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      
      - name: Disable Xdebug
      - run: sudo phpdismod xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-ansi --profile --no-interaction --no-scripts --no-suggest --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit --testdox --colors=always --exclude-group skipped