name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo phpdismod xdebug
      - run: composer install --no-progress --no-ansi --profile --no-interaction --no-scripts --no-suggest --prefer-dist
      - run: vendor/bin/phpunit --testdox --colors=always --exclude-group skipped